import Image from "next/image";
import pageStyles from "./page.module.css";

export default function Home() {
  return (
    // <main className={styles.main}>
      <div>
         <head>
           <title> Create Next App</title>
           <meta name="description" content="Generated by create next app"/>
           <link rel="icon" href="/favicon.ico"/> 
         </head>
         <section className={'${pageStyles.headingMd} ${pageStyles.padding1px}'}>
          <p>[John Ahn Introduction]</p>
          <p> (This is website)</p>
         </section>
         <section>
          <h2 className={pageStyles.headingLg}>Blog</h2>
          <ul className={pageStyles.list}>

          </ul>
         </section>
     </div>
      
  );
}


